'use client'

import { useState, useCallback } from 'react'
import type { Topic } from '@/schemas/user'

// Longer texts for better reading practice (~300-400 words each)
const sampleTexts: Record<Topic, string[]> = {
  dinosaurs: [
    `The mighty Tyrannosaurus Rex was one of the largest meat-eating dinosaurs that ever walked the Earth. It lived about sixty-five million years ago during the late Cretaceous period when dinosaurs ruled the planet. With teeth as long as bananas and jaws that could crush bones with a single bite, the T-Rex was truly the king of the dinosaurs. Scientists have found fossils all over North America showing where these incredible creatures once roamed freely. Baby T-Rex dinosaurs were covered in soft fluffy feathers when they first hatched from their eggs. They grew incredibly fast, gaining about five pounds every single day until they reached their massive adult size. Adult T-Rex could run as fast as twenty-five miles per hour despite their enormous size and weight. Their tiny arms were actually very strong and could lift heavy weights, though scientists still debate what they used them for. Some researchers think T-Rex hunted in packs like wolves do today, working together to take down even larger prey. The dinosaurs went extinct when a giant asteroid hit Earth millions of years ago, changing the climate dramatically. This asteroid impact created a huge dust cloud that blocked sunlight for months or even years. Without sunlight, plants died and the food chain collapsed completely. The T-Rex and all other non-bird dinosaurs disappeared from the Earth forever. However, scientists now believe that birds are actually living dinosaurs, the descendants of small feathered dinosaurs that survived the extinction event. When you see a chicken or a sparrow, you are looking at a modern dinosaur. Paleontologists continue to discover new dinosaur species every year, and each discovery teaches us more about these fascinating ancient creatures. Museums around the world display dinosaur skeletons and fossils, allowing people to imagine what life was like when these giants walked the Earth. The study of dinosaurs helps us understand how life evolved over millions of years and reminds us that even the mightiest creatures can disappear if conditions change too quickly.`,
    `Velociraptors were much smaller than movies show us, but they were still incredibly dangerous predators. They were only about the size of a turkey, standing about two feet tall at the hip, but what they lacked in size they made up for in intelligence and speed. These clever hunters had a large curved claw on each foot that they used like a knife to attack their prey. Scientists believe they probably hunted in groups to take down much bigger animals than themselves, using teamwork and strategy. Fossils found in Mongolia show that velociraptors had feathers covering their entire body, making them look more like strange birds than the scaly reptiles shown in movies. Their brains were quite large compared to other dinosaurs of their time, which is why scientists believe they were some of the smartest dinosaurs that ever lived. They could run very fast and jump high to catch their food, chasing down smaller animals with incredible agility. Velociraptors lived about seventy million years ago in what is now Asia and other parts of the world. Some scientists think modern birds are directly related to these ancient feathered hunters, sharing many similar features. The name velociraptor means swift thief, which perfectly describes how these dinosaurs lived and hunted. They likely used their intelligence to outsmart prey and avoid larger predators. Fossil evidence shows that velociraptors sometimes fought with other dinosaurs, including the heavily armored Protoceratops. One famous fossil shows a velociraptor and Protoceratops locked in combat, frozen in time by a sudden sandstorm. This discovery proved that velociraptors were fearless hunters willing to attack dangerous prey.`,
  ],
  space: [
    `Our solar system is an amazing place filled with planets, moons, asteroids, and countless wonders waiting to be explored. The Sun sits at the center, a massive ball of burning gas that provides light and heat to all the planets orbiting around it. Mercury is the closest planet to the Sun and experiences extreme temperatures, scorching hot during the day and freezing cold at night. Venus is covered in thick clouds that trap heat, making it even hotter than Mercury despite being farther from the Sun. Earth is the only planet we know of that has life, with its perfect distance from the Sun allowing water to exist in liquid form. Mars is called the red planet because of its rusty colored surface, created by iron oxide in its soil. Scientists have sent many robots to Mars to search for signs of ancient life and to prepare for future human missions. Jupiter is so massive that all other planets in our solar system could fit inside it with room to spare. Its famous Great Red Spot is a storm that has been raging for hundreds of years, larger than Earth itself. Saturn is known for its beautiful rings made of ice and rocks, stretching thousands of miles into space. These rings are so thin that if you could see them from the side, they would almost disappear. Uranus and Neptune are ice giants far away in the cold outer reaches of our solar system. Beyond Neptune lies the Kuiper Belt, home to Pluto and millions of other icy objects. Astronauts dream of one day traveling to Mars and establishing a permanent human presence on another planet. Space telescopes like Hubble and James Webb have shown us galaxies billions of light years away, expanding our understanding of the universe. Every discovery in space raises new questions about our place in the cosmos and whether we are alone in this vast universe.`,
    `Stars are giant balls of hot glowing gas floating far out in the darkness of space, and our Sun is just one of billions in our galaxy alone. The Sun is actually a medium-sized star compared to many others, though it appears huge because it is so close to Earth. Some stars are so enormous they could swallow our entire solar system without even noticing. When stars run out of fuel after billions of years, they can explode in spectacular events called supernovas, briefly outshining entire galaxies. The closest star to us besides the Sun is called Proxima Centauri, and it is over four light years away from Earth. That means light, the fastest thing in the universe, takes four whole years to travel from that star to our planet. Even our fastest spacecraft would take tens of thousands of years to reach the nearest star system. Astronomers use powerful telescopes on Earth and in space to study stars millions and billions of light years away. Some stars have planets orbiting around them, and scientists have discovered thousands of these exoplanets in recent years. They are searching for planets that might have water and conditions suitable for life as we know it. The night sky is filled with billions of stars, though we can only see a few thousand with our naked eyes. Ancient people looked at the stars and created constellations, patterns they imagined in the sky that helped them navigate and tell stories. Different cultures around the world created their own constellation myths, connecting the same stars into different pictures. Modern astronomers have cataloged millions of stars and continue to discover new ones using advanced technology. The study of stars has taught us about the history of our universe, from the Big Bang to the present day, and continues to reveal new mysteries about the cosmos we call home.`,
  ],
  robots: [
    `Robots are amazing machines that can do many tasks to help humans in ways that seemed like science fiction just a few decades ago. Some robots work in factories around the world, building cars, electronics, and other products with incredible speed and precision. These industrial robots never get tired, never need breaks, and can work twenty-four hours a day without making mistakes. Other robots are designed to explore dangerous places where humans cannot safely go, like the bottom of the ocean or the surface of other planets. Scientists have sent robots to Mars to study the red planet up close, taking pictures and collecting samples of rocks and soil. These Mars rovers have taught us more about our neighboring planet than centuries of telescope observations ever could. Medical robots help doctors perform surgery with incredible accuracy, making tiny incisions that human hands could never achieve alone. Some operations that once required weeks of recovery can now be done in hours with robotic assistance. Robots can also help people with disabilities, providing mobility assistance and helping them live more independent lives. Some robots can walk on two legs just like humans, though this is actually very difficult to program and balance. Engineers around the world are working on robots that can think and learn new things by themselves, using artificial intelligence. Robot vacuums have become common in many homes, cleaning floors while people relax or do other important tasks. Delivery robots are starting to appear on city streets, bringing packages and food to people without human drivers. In the future, robots might become our helpers, teachers, companions, and maybe even friends. Some people worry that robots might take jobs away from humans, while others believe robots will create new opportunities we cannot yet imagine. The development of robotics raises important questions about how humans and machines will work together in the years ahead.`,
  ],
  animals: [
    `Elephants are the largest land animals on Earth today, and they are among the most intelligent creatures in the animal kingdom. They live in close-knit family groups led by the oldest female, called the matriarch, who guides the herd using her decades of experience and wisdom. Baby elephants stay with their mothers for many years, learning important survival skills like where to find water during dry seasons and how to avoid predators. Elephants use their remarkable long trunks for many purposes: drinking water, grabbing food, communicating with other elephants, and even showing affection to family members. An elephant's trunk contains over forty thousand muscles and can pick up objects as small as a single blade of grass or as large as a heavy tree branch. These gentle giants have incredible memories and can remember places, routes, and other elephants for their entire long lives, which can span sixty years or more. African elephants have much larger ears than their Asian elephant cousins, which helps them stay cool in the hot African sun. Elephants spend up to sixteen hours every single day just eating, consuming hundreds of pounds of plants, leaves, bark, and fruit. Despite their enormous size, elephants are very social animals and show complex emotions like happiness, grief, and even what appears to be mourning when a family member dies. They have been observed covering dead elephants with branches and returning to visit the bones of deceased relatives years later. Conservation efforts around the world help protect elephants from poachers who hunt them for their valuable ivory tusks. Many countries have banned the ivory trade, but illegal hunting remains a serious threat to elephant populations. These magnificent creatures play an important role in their ecosystems, creating water holes that other animals use and spreading seeds through their droppings. Protecting elephants means protecting entire African and Asian ecosystems for future generations to enjoy and study.`,
  ],
  superheroes: [
    `Superheroes have captured human imagination for nearly a century, inspiring people to believe that anyone can make a difference in the world. These characters use their amazing powers and abilities to help people and fight against villains who threaten the innocent. Some heroes like Superman can fly through the sky faster than any airplane, speeding around the world in seconds to save people in danger. Others like the Hulk have super strength that lets them lift cars, buildings, and even mountains when they need to protect others. Many superheroes wear colorful costumes and masks to hide their secret identities, allowing them to live normal lives when they are not fighting crime. They often work alone, but sometimes they team up with other heroes to defeat powerful enemies that no single hero could stop. Spider-Man swings between tall buildings using his special sticky web shooters, combining his spider-like abilities with scientific genius. Batman uses incredible gadgets, martial arts training, and his brilliant detective mind to solve crimes and protect Gotham City. Unlike many superheroes, Batman has no special powers, proving that determination and training can be just as powerful as supernatural abilities. Wonder Woman is an Amazon warrior princess with incredible strength, a magic lasso that compels people to tell the truth, and indestructible bracelets that can deflect bullets. The Flash can run so fast that he becomes invisible to normal human eyes, able to vibrate through solid walls and even travel through time. These characters teach us valuable lessons about courage, responsibility, and the importance of helping others even when it is difficult or dangerous. Many superhero stories explore what it means to have great power and the responsibility that comes with it. They show us that heroes are not defined by their abilities but by their choices and their willingness to stand up for what is right. The popularity of superheroes continues to grow, with movies, television shows, and comic books reaching audiences around the world.`,
  ],
  ocean: [
    `The ocean is one of Earth's greatest mysteries, covering more than seventy percent of our planet's surface yet remaining largely unexplored by humans. It is home to millions of different species, from microscopic plankton that produce much of the oxygen we breathe to the enormous blue whale, the largest animal that has ever lived on Earth. The deepest part of the ocean is called the Mariana Trench, plunging nearly seven miles below the surface into complete darkness. Strange and wonderful creatures live in these deep waters where no sunlight can reach, surviving in crushing pressure and freezing temperatures that would kill most other life forms. Some deep-sea fish create their own light through a process called bioluminescence, using glowing lures to attract prey in the eternal darkness. Coral reefs are like underwater cities, bustling with colorful fish, sea turtles, and countless other creatures living among the intricate coral structures. These reefs are incredibly important ecosystems, supporting about one quarter of all ocean species despite covering less than one percent of the ocean floor. Dolphins are among the smartest creatures in the ocean, communicating with each other using clicks, whistles, and body language in complex ways that scientists are still trying to understand. Sea turtles travel thousands of miles across entire oceans, returning to the same beaches where they were born to lay their own eggs decades later. Sharks have been swimming in the oceans for over four hundred million years, outliving the dinosaurs and surviving multiple mass extinction events. Despite their fearsome reputation, most sharks are not dangerous to humans and play crucial roles in keeping ocean ecosystems healthy and balanced. Protecting our oceans has never been more important, as pollution, overfishing, and climate change threaten marine life around the world. The ocean provides food for billions of people, regulates our climate, and produces much of the oxygen in our atmosphere.`,
  ],
  sports: [
    `Soccer is the most popular sport in the world, with billions of fans on every continent cheering for their favorite teams. Players work together to kick a round ball across a grass field, trying to score goals by getting the ball past the opposing team's goalkeeper. The World Cup is the biggest soccer tournament on Earth, bringing together nations from around the globe every four years in a celebration of athletic excellence and international competition. Basketball was invented in Massachusetts in 1891 and has grown into a global phenomenon played and watched by millions of people worldwide. Players dribble, pass, and shoot the ball through a hoop mounted ten feet above the floor, combining athleticism with strategy and teamwork. The sport has produced legends like Michael Jordan, LeBron James, and countless others who have inspired young athletes around the world to pursue their dreams. Baseball has been called America's favorite pastime for over a century, with its unique combination of individual performances and team strategy. Players take turns batting, trying to hit a small ball thrown by the opposing pitcher and then running around bases to score runs for their team. Tennis involves two or four players hitting a small ball back and forth over a net, combining power, precision, and endurance in matches that can last for hours. Swimming is excellent exercise and Olympic swimmers can move through water at incredible speeds, their bodies perfectly adapted to cutting through the water with minimal resistance. Running is perhaps the oldest sport, requiring nothing more than a pair of shoes and the determination to put one foot in front of the other. Marathons attract thousands of runners who challenge themselves to cover twenty-six miles, pushing their bodies and minds to the limit. Playing sports teaches valuable life lessons about teamwork, discipline, perseverance, and how to handle both victory and defeat with grace. Athletes learn to set goals, work hard, and bounce back from setbacks, skills that serve them well throughout their lives.`,
  ],
  magic: [
    `Magic has fascinated humans for thousands of years, appearing in stories, legends, and myths from every culture around the world. Wizards and witches are the most famous magical beings, casting spells using wands, staffs, ancient words, or simply the power of their minds. In many stories, magic follows specific rules and requires years of study to master, much like learning any complex skill in the real world. Some magic users can transform objects into completely different things, turning lead into gold or mice into horses with a wave of their wand. Potions are another common form of magic, special drinks brewed from rare ingredients that can give people amazing powers, heal terrible wounds, or cause dramatic transformations. Magical schools appear in many fantasy stories, places where young wizards learn to control their special abilities under the guidance of experienced teachers. Students might study spellcasting, potion making, magical creatures, and the history of magic in hidden schools far from the ordinary world. Dragons are among the most famous magical creatures, enormous reptiles that breathe fire and often guard vast treasures in their mountain caves. Despite their fearsome reputation, some stories portray dragons as wise beings who can live for thousands of years and possess ancient knowledge. Unicorns are beautiful horses with a single spiral horn on their forehead, often associated with purity, healing, and the protection of the innocent. Fairies are tiny magical beings with delicate wings who sometimes help humans, granting wishes to those who treat them with kindness and respect. Merlin is perhaps the most famous wizard in Western literature, the advisor to King Arthur who helped shape the legendary kingdom of Camelot. Magic in stories often represents hope, wonder, and the belief that extraordinary things are possible if we only believe strongly enough. These tales remind us that imagination has the power to create entire worlds filled with impossible wonders and endless adventure.`,
  ],
  nature: [
    `Nature surrounds us with incredible beauty and complexity, from the tiniest insects to the mightiest mountains stretching toward the sky. Forests are home to countless animals, plants, fungi, and microorganisms, all living together in interconnected ecosystems that have evolved over millions of years. Trees are the giants of the plant kingdom, producing the oxygen that all animals need to breathe and providing shelter and food for countless creatures. A single large tree can absorb hundreds of pounds of carbon dioxide each year while releasing enough oxygen for several people to breathe. Rainforests near the equator contain more species of plants and animals than any other environment on Earth, though scientists estimate we have discovered only a fraction of the life forms that exist there. These tropical forests also play a crucial role in regulating Earth's climate by absorbing carbon dioxide and releasing moisture into the atmosphere. Mountains are formed over millions of years when enormous pieces of Earth's crust push against each other, slowly rising higher and higher until they tower above the surrounding landscape. Rivers carry water from mountain peaks down through valleys and plains, eventually reaching the oceans and completing the water cycle that sustains all life. Deserts may appear empty and lifeless at first glance, but they are actually home to many specially adapted plants and animals that have evolved to survive with very little water. Seasons change because Earth is tilted on its axis as it orbits the Sun, giving us the rhythm of spring, summer, autumn, and winter that shapes life in most parts of the world. Birds migrate thousands of miles every year, traveling between summer and winter homes following ancient routes their ancestors discovered long ago. Bees are incredibly important pollinators, helping flowers reproduce and making possible the fruits and vegetables that humans and other animals depend on for food. Spending time in nature has been shown to reduce stress, improve mood, and help people feel more connected to the living world around them.`,
  ],
  adventures: [
    `Adventure has called to humans throughout history, driving explorers to discover new lands, scale towering peaks, and venture into the unknown reaches of our world. Some adventurers have climbed the highest mountains on Earth, facing extreme cold, dangerous avalanches, and thin air that makes every breath a struggle. Mount Everest, the tallest mountain in the world, has attracted climbers from every nation, though reaching its summit remains one of the greatest challenges any human can undertake. Other explorers have traveled to the frozen poles of our planet, enduring months of darkness, temperatures far below zero, and isolation from the rest of humanity. Deep sea adventurers dive beneath the waves to explore shipwrecks, underwater caves, and the mysterious depths where strange creatures live in eternal darkness. The ocean floor remains largely unmapped, with new discoveries waiting for those brave enough to venture into the deep. The Amazon rainforest is one of the last great frontiers for modern explorers, a vast wilderness so dense and unexplored that new species are discovered there every year. Indigenous peoples have lived in these forests for thousands of years, possessing knowledge of plants and animals that scientists are only beginning to understand. Ancient maps sometimes show mysterious places marked with warnings like "here be dragons," inviting adventurers to discover what really lies beyond the known world. Treasure hunters have spent lifetimes searching for lost gold, sunken ships full of valuables, and artifacts from ancient civilizations buried beneath the earth. Survival skills help adventurers find food, water, and shelter in the wild, turning hostile environments into temporary homes. Navigation has been crucial to exploration, with compasses, maps, and now GPS technology guiding travelers through unfamiliar territories. The greatest adventures often begin with simple curiosity and the courage to ask "what if" and "why not." Every person has the potential for adventure, whether exploring distant lands or simply discovering new wonders in their own neighborhood.`,
  ],
  science: [
    `Science is humanity's greatest tool for understanding the universe, allowing us to ask questions about everything from the smallest atoms to the largest galaxies. Scientists follow a method of observation, hypothesis, experimentation, and analysis that has led to discoveries that changed the world. Chemistry studies what things are made of at the molecular level, exploring how atoms combine to form everything from water to diamonds to the cells in our bodies. Simple experiments like mixing baking soda and vinegar demonstrate chemical reactions that you can try at home, creating bubbling foam as acids and bases react. Physics helps us understand the fundamental forces that govern our universe, explaining why objects fall, how light travels, and what holds atoms together. Isaac Newton discovered the laws of motion and gravity while Albert Einstein revolutionized our understanding of space, time, and energy with his theories of relativity. Biology is the study of living things, from the smallest bacteria that we cannot see without microscopes to the enormous whales swimming through our oceans. Biologists have discovered how DNA carries the instructions for life, how evolution shapes species over millions of years, and how ecosystems function as interconnected webs of life. The scientific method provides a fair and organized way to test ideas, allowing researchers to distinguish between what we think might be true and what evidence actually supports. Microscopes have revealed entire worlds invisible to our naked eyes, showing us the bacteria, cells, and tiny structures that make up living things. Space telescopes orbit high above Earth's atmosphere, capturing images of galaxies billions of light years away and helping us understand the history and structure of our universe. Scientists from around the world work together, sharing discoveries and building on each other's work to solve problems that affect all of humanity. Medical researchers develop vaccines and treatments that save millions of lives, while environmental scientists study how to protect our planet for future generations.`,
  ],
  minecraft: [
    `Minecraft has become one of the most popular video games in history, inspiring millions of players to build, explore, and create in a world made entirely of blocks. The game starts with nothing but your character's hands, and from there you must gather resources to survive your first night before dangerous creatures spawn in the darkness. Wood from trees becomes your first tool, a simple wooden pickaxe that lets you mine stone and begin building more advanced equipment. As you progress, you discover iron, gold, and eventually the precious diamonds that let you craft the strongest tools and armor in the game. Survival mode challenges players to find food, build shelter, and protect themselves from zombies, skeletons, spiders, and the dreaded Creepers that explode when they get too close. The Nether is an alternate dimension accessible through portals made of obsidian, a dangerous realm of lava, fire, and hostile creatures unlike anything in the normal world. Surviving in the Nether requires careful preparation and quick reflexes, as one wrong step can send you plunging into lakes of burning lava. Villages scattered throughout the world contain friendly villagers who will trade useful items for emeralds, offering everything from enchanted books to diamond armor. Redstone is Minecraft's version of electricity, a special dust that lets creative players build working machines, automatic doors, traps, and even simple computers within the game. The possibilities for building in Minecraft are nearly endless, with players constructing everything from simple houses to massive castles, working calculators, and recreations of famous real-world buildings. Creative mode removes survival elements entirely, giving players unlimited resources to build whatever they can imagine without worrying about monsters or hunger. Multiplayer servers allow friends to explore and build together, creating shared worlds where communities can collaborate on enormous projects. Minecraft teaches valuable skills including creativity, problem-solving, resource management, and planning, all while providing hours of entertainment.`,
  ],
  pokemon: [
    `Pokemon has captured the hearts of fans around the world for over twenty-five years, inspiring video games, trading cards, television shows, movies, and countless other forms of entertainment. The world of Pokemon is filled with amazing creatures that have special powers and abilities, from the fire-breathing Charizard to the psychic Mewtwo to the adorable electric mouse Pikachu. Trainers begin their journey at age ten, choosing their first Pokemon and setting out to explore the world, catch new creatures, and become the very best like no one ever was. Each Pokemon has one or two types that determine its strengths and weaknesses in battle, creating a complex system of strategy that rewards careful planning and team building. Fire-type Pokemon are strong against grass types but weak against water, while electric types dominate flying Pokemon but struggle against ground types. Gym battles test trainers against powerful leaders who specialize in specific types, awarding badges to those who prove their skill and determination. Eight gym badges earn a trainer the right to challenge the Elite Four and Champion, the most powerful trainers in the region. Evolution transforms Pokemon into stronger forms, sometimes changing their types and abilities dramatically as they grow through battle experience. Some Pokemon only evolve when traded, exposed to special stones, or when their friendship with their trainer reaches high levels. Legendary Pokemon are incredibly rare and powerful, often connected to ancient myths and playing important roles in the stories of each Pokemon region. The bond between trainers and their Pokemon is central to every Pokemon story, showing how friendship, trust, and working together can overcome any challenge. Pokemon Centers heal tired and injured Pokemon, allowing trainers to continue their adventures without permanent harm to their beloved partners. The dream of catching all Pokemon drives many trainers to explore every corner of the world, seeking rare species and completing their Pokedex.`,
  ],
  cars: [
    `Automobiles have transformed human civilization over the past century, making it possible to travel farther and faster than our ancestors could have ever imagined. The first cars were invented in the late 1800s, strange contraptions that looked nothing like modern vehicles and moved at speeds barely faster than walking. Henry Ford revolutionized the automobile industry with his assembly line production method, making cars affordable for ordinary families for the first time. Early cars required hand cranks to start their engines, had no heaters or air conditioning, and traveled on unpaved roads that turned to mud whenever it rained. Today's cars are engineering marvels, combining thousands of precisely manufactured parts into machines that can travel smoothly at highway speeds for hundreds of thousands of miles. Race cars push the limits of automotive technology, reaching speeds over two hundred miles per hour on specially designed tracks with professional drivers at the controls. Formula One represents the pinnacle of racing technology, with cars that cost millions of dollars and teams of engineers constantly seeking tiny advantages in speed and performance. Electric cars have become increasingly popular as technology improves, using batteries and electric motors instead of gasoline engines that produce harmful emissions. Some experts predict that most new cars will be electric within the next few decades, helping to reduce air pollution and combat climate change. Self-driving cars are being developed by companies around the world, using cameras, sensors, and artificial intelligence to navigate roads without human drivers. These autonomous vehicles could revolutionize transportation, reducing accidents caused by human error and providing mobility for people who cannot drive themselves. Classic cars from decades past are lovingly restored and collected by enthusiasts who appreciate their historical significance and unique designs. The engine is the heart of any car, converting fuel into the motion that carries us wherever we want to go. Future cars might look very different from today's vehicles, perhaps flying through the air or traveling on networks of automated highways that manage traffic flow perfectly.`,
  ],
  music: [
    `Music is one of humanity's oldest and most universal forms of expression, with evidence of musical instruments dating back tens of thousands of years. Every culture on Earth has developed its own musical traditions, from the complex orchestral compositions of Europe to the rhythmic drumming of Africa to the meditative sounds of Asian instruments. Instruments come in countless varieties, from stringed instruments like guitars, violins, and pianos to wind instruments like flutes and trumpets to percussion instruments like drums and cymbals. Each instrument produces sound in its own unique way, and skilled musicians spend years learning to coax beautiful melodies from their chosen instruments. Singing might be the oldest form of music, requiring no equipment beyond the human voice that everyone possesses from birth. Classical music reached its peak during the eighteenth and nineteenth centuries, when composers like Mozart, Beethoven, and Bach created works that are still performed and celebrated today. These masterpieces demonstrate the incredible complexity possible in music, with multiple instruments playing different parts that combine into beautiful harmonies. Rock and roll exploded onto the scene in the 1950s, combining elements of blues, country, and rhythm and blues into an energetic new style that appealed especially to young people. The Beatles, Rolling Stones, and countless other bands changed music forever, inspiring generations of musicians and fans around the world. Hip hop emerged from New York City in the 1970s, combining rhythmic spoken word with beats and samples to create a new form of musical expression that has become a global phenomenon. Learning to play an instrument requires patience and practice, but the rewards of creating music are worth the effort for millions of people. Music has the power to change our moods almost instantly, making us feel happy, sad, energetic, or calm depending on the rhythms and melodies we hear. Concerts and music festivals bring together thousands of fans to share the experience of live music, creating memorable moments of collective joy and celebration. Creating your own music, whether by playing instruments, singing, or using computers, is a wonderful way to express emotions and tell stories that words alone cannot capture.`,
  ],
}

export function useTextGenerator() {
  const [isLoading, setIsLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const generateText = useCallback(async (topic: Topic, _age?: number): Promise<string> => {
    setIsLoading(true)
    setError(null)

    try {
      await new Promise(resolve => setTimeout(resolve, 200))

      const texts = sampleTexts[topic] || sampleTexts.adventures
      const randomText = texts[Math.floor(Math.random() * texts.length)]

      return randomText
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Failed to generate text'
      setError(message)
      throw err
    } finally {
      setIsLoading(false)
    }
  }, [])

  // Helper to collect and shuffle texts from topics
  const collectTexts = useCallback((topics: Topic[], prioritizeUserTopics: boolean = true): string[] => {
    const texts: string[] = []
    const topicsToUse = topics.length > 0 ? topics : ['adventures' as Topic]
    const allTopics = Object.keys(sampleTexts) as Topic[]

    if (prioritizeUserTopics) {
      // First, add texts from user's selected topics
      for (const topic of topicsToUse) {
        const topicTexts = sampleTexts[topic] || sampleTexts.adventures
        for (const text of topicTexts) {
          texts.push(text)
        }
      }

      // Then add texts from other topics
      for (const topic of allTopics) {
        if (!topicsToUse.includes(topic)) {
          const topicTexts = sampleTexts[topic]
          for (const text of topicTexts) {
            texts.push(text)
          }
        }
      }
    } else {
      // Just get all texts
      for (const topic of allTopics) {
        const topicTexts = sampleTexts[topic]
        for (const text of topicTexts) {
          texts.push(text)
        }
      }
    }

    // Shuffle the texts array for variety
    return texts.sort(() => Math.random() - 0.5)
  }, [])

  // Generate single topic text (~350-400 words) - used for baseline
  const generateForTopics = useCallback(async (topics: Topic[], age?: number): Promise<string> => {
    if (topics.length === 0) {
      return generateText('adventures', age)
    }
    const randomTopic = topics[Math.floor(Math.random() * topics.length)]
    return generateText(randomTopic, age)
  }, [generateText])

  // Generate medium text (~4500 words) for most exercises
  // At 900 WPM, that's 5 minutes of reading - enough for Pointer Wand, Silent Shadow, Side Scanner
  const generateMediumText = useCallback(async (topics: Topic[], _age?: number): Promise<string> => {
    const allTexts = collectTexts(topics, true)

    // Each text is ~350-400 words. For ~4500 words, we need ~12 texts
    const textsNeeded = Math.min(12, allTexts.length)
    const selectedTexts = allTexts.slice(0, textsNeeded)

    return selectedTexts.join(' ')
  }, [collectTexts])

  // Generate extra long text for Time Boss (~10,000+ words)
  // Time Boss is 10 minutes total (4+3+2+1). At 900 WPM, that's ~9000 words needed!
  const generateLongText = useCallback(async (topics: Topic[], _age?: number): Promise<string> => {
    const allTexts = collectTexts(topics, true)
    // Return all texts combined (should be ~10,000+ words)
    return allTexts.join(' ')
  }, [collectTexts])

  return {
    generateText,
    generateForTopics,
    generateMediumText,
    generateLongText,
    isLoading,
    error,
  }
}
